#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ReasonApplication.Resource", IsApplication=true)]

namespace ReasonApplication
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f040000
			public const int config_ui_enableFadingMarquee = 2130968576;
			
			private Boolean()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int btAuth = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int btFb = 2131099662;
			
			// aapt resource value: 0x7f060008
			public const int btSendComment = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int btStandalone = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int lbError = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int lbName = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int tab1 = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int tab2 = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int tabHost1 = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int tbLogin = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int tbPass = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int tbTaskComment = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int tbTaskText = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int textView1 = 2131099651;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int HomeScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LoginAuth = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int login = 2131034114;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
